name: Update

on:
  push:
  schedule:
    - cron: 0 8,18 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: |
        # 央视源
        rm -f CCTV.m3u && wget https://live.fanmingming.com/tv/m3u/ipv6.m3u -O CCTV.m3u
        sed -i -n '/央视/,+1p' CCTV.m3u
        sed -i '1i #EXTM3U' CCTV.m3u
        sed -i '/^\s*$/d' CCTV.m3u
        # 卫视源
        rm -f CNTV.m3u && wget https://live.fanmingming.com/tv/m3u/ipv6.m3u -O CNTV.m3u
        sed -i '/央视/,+1d' CNTV.m3u
        sed -i '/^\s*$/d' CNTV.m3u
        # 直播台平
        rm -f ONLINE.m3u && wget https://raw.githubusercontent.com/popeyelau/assets/main/live/youtube.m3u -O ONLINE.m3u
        # 整合源
        rm -f IPTV.m3u && touch IPTV.m3u
        cat CCTV.m3u >> IPTV.m3u
        cat CNTV.m3u >> IPTV.m3u
        cat ONLINE.m3u >> IPTV.m3u
        sed -i '/#EXTM3U/d' IPTV.m3u
        sed -i '1i #EXTM3U' IPTV.m3u
        sed -i '/^\s*$/d' IPTV.m3u
        # 节目源
        rm -f EPG.xml && wget http://epg.51zmt.top:8000/e.xml -O EPG.xml
        
    - name: Commit
      run: |
        git config --local user.email "popeyelau@gmail.com"
        git config --local user.name "Popeye Lau"
        git pull
        git add .
        git commit -m "update" || true
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
