name: Update

on:
  push:
  schedule:
    - cron: 0 8,18 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update
      run: |
        # 电视
        rm -f tv.m3u && wget https://gist.githubusercontent.com/popeyelau/8678ff0ced397b2a74c3807670f4ace6/raw/tv.m3u -O tv.m3u
        # 电影
        rm -f movie.m3u && wget https://gist.githubusercontent.com/popeyelau/8678ff0ced397b2a74c3807670f4ace6/raw/movie.m3u -O movie.m3u
        # 综艺
        rm -f variety.m3u && wget https://gist.githubusercontent.com/popeyelau/8678ff0ced397b2a74c3807670f4ace6/raw/variety.m3u -O variety.m3u
        # 电视直播
        rm -f iptv.m3u && wget https://gist.githubusercontent.com/popeyelau/5452403b0f165d48766b186e4f2e2d9b/raw/list.m3u -O iptv.m3u
        # 节目源
        rm -f epg.xml.gz https://epg.zsdc.eu.org/t.xml.gz -O epg.xml.gz
    - name: Commit
      run: |
        git config --local user.email "popeyelau@gmail.com"
        git config --local user.name "Popeye Lau"
        git pull
        git add .
        git commit -m "update" || true
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
